<?php
/** @var $block Sigma\FreeShippingBar\Block\Freeshipping */
?>

<?php if ($block->isFreeShippingEligible()): ?>
    <div id="free-shipping-banner" data-bind="scope: 'free-shipping-banner'">
        <!-- ko template:getTemplate() --><!-- /ko -->
    </div>

    <script type="text/x-magento-init">
        {
             "#free-shipping-banner" : {
                "Magento_Ui/js/core/app" :<?= $block->getJsLayout() ?>
             }
        }
    </script>

    <script>
        window.freeShippingThreshold = '<?php echo $block->getFreeShippingAmount(); ?>';
    </script>
<?php endif; ?>
