<div class="field phone_number">
    <h2 class="tital-phone-number"><?php /* @escapeNotVerified */ echo __('Addition Information') ?></h2>
    <label class="label" for="phone_number"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
    <div class="control">
        <input type="text" id="phone_number" name="phone_number"  title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text" autocomplete="off">
    </div>
</div>
